//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.239
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Torshify.Radio.Spotify.LoginService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://schemas.torshify/v1", ConfigurationName="LoginService.LoginService", CallbackContract=typeof(Torshify.Radio.Spotify.LoginService.LoginServiceCallback))]
    public interface LoginService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://schemas.torshify/v1/LoginService/Subscribe", ReplyAction="http://schemas.torshify/v1/LoginService/SubscribeResponse")]
        void Subscribe();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://schemas.torshify/v1/LoginService/Unsubscribe", ReplyAction="http://schemas.torshify/v1/LoginService/UnsubscribeResponse")]
        void Unsubscribe();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://schemas.torshify/v1/LoginService/IsLoggedIn", ReplyAction="http://schemas.torshify/v1/LoginService/IsLoggedInResponse")]
        bool IsLoggedIn();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://schemas.torshify/v1/LoginService/GetRememberedUser", ReplyAction="http://schemas.torshify/v1/LoginService/GetRememberedUserResponse")]
        string GetRememberedUser();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://schemas.torshify/v1/LoginService/Login", ReplyAction="http://schemas.torshify/v1/LoginService/LoginResponse")]
        void Login(string userName, string password, bool remember);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://schemas.torshify/v1/LoginService/ForgetRememberedUser", ReplyAction="http://schemas.torshify/v1/LoginService/ForgetRememberedUserResponse")]
        void ForgetRememberedUser();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://schemas.torshify/v1/LoginService/Relogin", ReplyAction="http://schemas.torshify/v1/LoginService/ReloginResponse")]
        void Relogin();
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface LoginServiceCallback {
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://schemas.torshify/v1/LoginService/OnLoggedIn")]
        void OnLoggedIn();
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://schemas.torshify/v1/LoginService/OnLoginError")]
        void OnLoginError(string message);
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://schemas.torshify/v1/LoginService/OnLoggedOut")]
        void OnLoggedOut();
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://schemas.torshify/v1/LoginService/OnPing")]
        void OnPing();
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface LoginServiceChannel : Torshify.Radio.Spotify.LoginService.LoginService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class LoginServiceClient : System.ServiceModel.DuplexClientBase<Torshify.Radio.Spotify.LoginService.LoginService>, Torshify.Radio.Spotify.LoginService.LoginService {
        
        public LoginServiceClient(System.ServiceModel.InstanceContext callbackInstance) : 
                base(callbackInstance) {
        }
        
        public LoginServiceClient(System.ServiceModel.InstanceContext callbackInstance, string endpointConfigurationName) : 
                base(callbackInstance, endpointConfigurationName) {
        }
        
        public LoginServiceClient(System.ServiceModel.InstanceContext callbackInstance, string endpointConfigurationName, string remoteAddress) : 
                base(callbackInstance, endpointConfigurationName, remoteAddress) {
        }
        
        public LoginServiceClient(System.ServiceModel.InstanceContext callbackInstance, string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(callbackInstance, endpointConfigurationName, remoteAddress) {
        }
        
        public LoginServiceClient(System.ServiceModel.InstanceContext callbackInstance, System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(callbackInstance, binding, remoteAddress) {
        }
        
        public void Subscribe() {
            base.Channel.Subscribe();
        }
        
        public void Unsubscribe() {
            base.Channel.Unsubscribe();
        }
        
        public bool IsLoggedIn() {
            return base.Channel.IsLoggedIn();
        }
        
        public string GetRememberedUser() {
            return base.Channel.GetRememberedUser();
        }
        
        public void Login(string userName, string password, bool remember) {
            base.Channel.Login(userName, password, remember);
        }
        
        public void ForgetRememberedUser() {
            base.Channel.ForgetRememberedUser();
        }
        
        public void Relogin() {
            base.Channel.Relogin();
        }
    }
}
