//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.239
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Torshify.Radio.Spotify.PlayerControlService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://schemas.torshify/v1", ConfigurationName="PlayerControlService.PlayerControlService", CallbackContract=typeof(Torshify.Radio.Spotify.PlayerControlService.PlayerControlServiceCallback))]
    public interface PlayerControlService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://schemas.torshify/v1/PlayerControlService/GetStatus", ReplyAction="http://schemas.torshify/v1/PlayerControlService/GetStatusResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(Torshify.Origo.Contracts.V1.NotLoggedInFault), Action="http://schemas.torshify/v1/PlayerControlService/GetStatusNotLoggedInFaultFault", Name="NotLoggedInFault", Namespace="http://schemas.datacontract.org/2004/07/Torshify.Origo.Contracts.V1")]
        Torshify.Origo.Contracts.V1.PlayerStatus GetStatus();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://schemas.torshify/v1/PlayerControlService/TogglePause", ReplyAction="http://schemas.torshify/v1/PlayerControlService/TogglePauseResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(Torshify.Origo.Contracts.V1.NotLoggedInFault), Action="http://schemas.torshify/v1/PlayerControlService/TogglePauseNotLoggedInFaultFault", Name="NotLoggedInFault", Namespace="http://schemas.datacontract.org/2004/07/Torshify.Origo.Contracts.V1")]
        void TogglePause();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://schemas.torshify/v1/PlayerControlService/SetVolume", ReplyAction="http://schemas.torshify/v1/PlayerControlService/SetVolumeResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(Torshify.Origo.Contracts.V1.NotLoggedInFault), Action="http://schemas.torshify/v1/PlayerControlService/SetVolumeNotLoggedInFaultFault", Name="NotLoggedInFault", Namespace="http://schemas.datacontract.org/2004/07/Torshify.Origo.Contracts.V1")]
        void SetVolume(float volume);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://schemas.torshify/v1/PlayerControlService/GetVolume", ReplyAction="http://schemas.torshify/v1/PlayerControlService/GetVolumeResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(Torshify.Origo.Contracts.V1.NotLoggedInFault), Action="http://schemas.torshify/v1/PlayerControlService/GetVolumeNotLoggedInFaultFault", Name="NotLoggedInFault", Namespace="http://schemas.datacontract.org/2004/07/Torshify.Origo.Contracts.V1")]
        float GetVolume();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://schemas.torshify/v1/PlayerControlService/Seek", ReplyAction="http://schemas.torshify/v1/PlayerControlService/SeekResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(Torshify.Origo.Contracts.V1.NotLoggedInFault), Action="http://schemas.torshify/v1/PlayerControlService/SeekNotLoggedInFaultFault", Name="NotLoggedInFault", Namespace="http://schemas.datacontract.org/2004/07/Torshify.Origo.Contracts.V1")]
        void Seek(double milliseconds);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://schemas.torshify/v1/PlayerControlService/Subscribe", ReplyAction="http://schemas.torshify/v1/PlayerControlService/SubscribeResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(Torshify.Origo.Contracts.V1.NotLoggedInFault), Action="http://schemas.torshify/v1/PlayerControlService/SubscribeNotLoggedInFaultFault", Name="NotLoggedInFault", Namespace="http://schemas.datacontract.org/2004/07/Torshify.Origo.Contracts.V1")]
        void Subscribe();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://schemas.torshify/v1/PlayerControlService/Unsubscribe", ReplyAction="http://schemas.torshify/v1/PlayerControlService/UnsubscribeResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(Torshify.Origo.Contracts.V1.NotLoggedInFault), Action="http://schemas.torshify/v1/PlayerControlService/UnsubscribeNotLoggedInFaultFault", Name="NotLoggedInFault", Namespace="http://schemas.datacontract.org/2004/07/Torshify.Origo.Contracts.V1")]
        void Unsubscribe();
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface PlayerControlServiceCallback {
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://schemas.torshify/v1/PlayerControlService/OnTrackChanged")]
        void OnTrackChanged(Torshify.Origo.Contracts.V1.Track track);
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://schemas.torshify/v1/PlayerControlService/OnTrackComplete")]
        void OnTrackComplete(Torshify.Origo.Contracts.V1.Track track);
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://schemas.torshify/v1/PlayerControlService/OnElapsed")]
        void OnElapsed(double elapsedMs, double totalMs);
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://schemas.torshify/v1/PlayerControlService/OnPlayStateChanged")]
        void OnPlayStateChanged(bool isPlaying);
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://schemas.torshify/v1/PlayerControlService/OnVolumeChanged")]
        void OnVolumeChanged(float volume);
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://schemas.torshify/v1/PlayerControlService/OnPing")]
        void OnPing();
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface PlayerControlServiceChannel : Torshify.Radio.Spotify.PlayerControlService.PlayerControlService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class PlayerControlServiceClient : System.ServiceModel.DuplexClientBase<Torshify.Radio.Spotify.PlayerControlService.PlayerControlService>, Torshify.Radio.Spotify.PlayerControlService.PlayerControlService {
        
        public PlayerControlServiceClient(System.ServiceModel.InstanceContext callbackInstance) : 
                base(callbackInstance) {
        }
        
        public PlayerControlServiceClient(System.ServiceModel.InstanceContext callbackInstance, string endpointConfigurationName) : 
                base(callbackInstance, endpointConfigurationName) {
        }
        
        public PlayerControlServiceClient(System.ServiceModel.InstanceContext callbackInstance, string endpointConfigurationName, string remoteAddress) : 
                base(callbackInstance, endpointConfigurationName, remoteAddress) {
        }
        
        public PlayerControlServiceClient(System.ServiceModel.InstanceContext callbackInstance, string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(callbackInstance, endpointConfigurationName, remoteAddress) {
        }
        
        public PlayerControlServiceClient(System.ServiceModel.InstanceContext callbackInstance, System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(callbackInstance, binding, remoteAddress) {
        }
        
        public Torshify.Origo.Contracts.V1.PlayerStatus GetStatus() {
            return base.Channel.GetStatus();
        }
        
        public void TogglePause() {
            base.Channel.TogglePause();
        }
        
        public void SetVolume(float volume) {
            base.Channel.SetVolume(volume);
        }
        
        public float GetVolume() {
            return base.Channel.GetVolume();
        }
        
        public void Seek(double milliseconds) {
            base.Channel.Seek(milliseconds);
        }
        
        public void Subscribe() {
            base.Channel.Subscribe();
        }
        
        public void Unsubscribe() {
            base.Channel.Unsubscribe();
        }
    }
}
