//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.239
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Torshify.Radio.EchoNest.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Torshify.Radio.EchoNest.Properties.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @Add_To_Favorites.
        /// </summary>
        internal static string Add_To_Favorites {
            get {
                return ResourceManager.GetString("Add_To_Favorites", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @Add_To_Queue.
        /// </summary>
        internal static string Add_To_Queue {
            get {
                return ResourceManager.GetString("Add_To_Queue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @Ban_Term.
        /// </summary>
        internal static string Ban_Term {
            get {
                return ResourceManager.GetString("Ban_Term", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @Decrease_Boost_Term.
        /// </summary>
        internal static string Decrease_Boost_Term {
            get {
                return ResourceManager.GetString("Decrease_Boost_Term", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @Hate.
        /// </summary>
        internal static string Hate {
            get {
                return ResourceManager.GetString("Hate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @Increase_Boost_Term.
        /// </summary>
        internal static string Increase_Boost_Term {
            get {
                return ResourceManager.GetString("Increase_Boost_Term", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @Love.
        /// </summary>
        internal static string Love {
            get {
                return ResourceManager.GetString("Love", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @Love_Or_Hate.
        /// </summary>
        internal static string Love_Or_Hate {
            get {
                return ResourceManager.GetString("Love_Or_Hate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @Love_Or_Hate_Watermark.
        /// </summary>
        internal static string Love_Or_Hate_Watermark {
            get {
                return ResourceManager.GetString("Love_Or_Hate_Watermark", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @Play_Album.
        /// </summary>
        internal static string Play_Album {
            get {
                return ResourceManager.GetString("Play_Album", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @Remove.
        /// </summary>
        internal static string Remove {
            get {
                return ResourceManager.GetString("Remove", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @Require_Term.
        /// </summary>
        internal static string Require_Term {
            get {
                return ResourceManager.GetString("Require_Term", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @Search_For_Similar_Artist.
        /// </summary>
        internal static string Search_For_Similar_Artist {
            get {
                return ResourceManager.GetString("Search_For_Similar_Artist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @Search_For_Similar_Artist_Watermark.
        /// </summary>
        internal static string Search_For_Similar_Artist_Watermark {
            get {
                return ResourceManager.GetString("Search_For_Similar_Artist_Watermark", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @Search_For_Song_Or_Artist.
        /// </summary>
        internal static string Search_For_Song_Or_Artist {
            get {
                return ResourceManager.GetString("Search_For_Song_Or_Artist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @Skip_Track.
        /// </summary>
        internal static string Skip_Track {
            get {
                return ResourceManager.GetString("Skip_Track", resourceCulture);
            }
        }
    }
}
